# config/packages/nelmio_cors.yaml
nelmio_cors:
    defaults:
        allow_origin: ['http://localhost:3000']
        allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
        allow_headers: ['Content-Type', 'Authorization']
        allow_credentials: true
        expose_headers: ['Authorization', 'Content-Type']
    paths:
        '^/api/': 
            allow_origin: ['http://localhost:3000']
            allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
